server {
	listen 5173;

	location ~* \.(css|js|svg|woff2?|ttf|png|jpe?g|gif|ico|webp)$ {
		try_files $uri =404;
		expires 1y;
		add_header Cache-Control "public, immutable";
	}

	location / {
		root /usr/share/nginx/html;
		index index.html index.htm;
		try_files $uri $uri/ /index.html =404;
	}

	include /etc/nginx/extra-conf.d/*.conf;
}
