# Daily Energy — developer entry points.
#
# The environment is described by `.env` + `.env.mode` (generated by
# scripts/configure.sh). Compose profiles are derived from those files, so a
# single `make up` starts whatever mode was last configured.

DC          ?= sudo docker compose
CONFIGURE   := ./scripts/configure.sh
MODE_FILE   := .env.mode

# Read MODE / COMPOSE_PROFILES from .env.mode when present.
-include $(MODE_FILE)
MODE            ?= unset
COMPOSE_PROFILES ?=

# Build the `--profile` flags from the space-separated COMPOSE_PROFILES list.
PROFILE_FLAGS = $(foreach p,$(COMPOSE_PROFILES),--profile $(p))

.PHONY: help configure configure-prod configure-dev configure-full \
        up down stop logs restart ps build \
        dev dev-backend dev-full \
        prod build-frontend build-backend format

# ---------------------------------------------------------------------------
# Help
# ---------------------------------------------------------------------------
help:
	@echo "Daily Energy — доступные команды:"
	@echo ""
	@echo "  make configure        Интерактивное меню выбора режима"
	@echo "  make configure-prod   Режим 'prod' (без меню)"
	@echo "  make configure-dev    Режим 'dev' — только бэкенд"
	@echo "  make configure-full   Режим 'dev-full' — локальный API + фронтенд"
	@echo ""
	@echo "  make up               Запустить стек текущего режима (build + up)"
	@echo "  make down             Остановить стек и удалить тома"
	@echo "  make stop             Остановить стек, сохранив данные БД"
	@echo "  make logs             Смотреть логи"
	@echo "  make ps               Статус контейнеров"
	@echo "  make restart          Перезапустить стек"
	@echo ""
	@echo "  make dev              configure-dev + up + logs"
	@echo "  make dev-backend      configure-dev + up + logs (только бэк)"
	@echo "  make dev-full         configure-full + up + logs (локальный API + фронт)"
	@echo "  make prod             configure-prod + up + logs"
	@echo ""
	@echo "  make format           gofmt + prettier (если доступен)"
	@echo ""
	@echo "Текущий режим: $(MODE) (профили: $(COMPOSE_PROFILES))"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
configure:
	$(CONFIGURE)

configure-prod:
	$(CONFIGURE) prod

configure-dev:
	$(CONFIGURE) dev

configure-full:
	$(CONFIGURE) full

# ---------------------------PROFILE_FL------------------------------------------------
# Compose helpers (profiles come from .env.mode)
# ---------------------------------------------------------------------------
guard-mode:
	@if [ -z "$(COMPOSE_PROFILES)" ]; then \
		echo "Режим не настроен. Сначала выполните: make configure"; \
		exit 1; \
	fi

up: guard-mode
	$(DC) $(PROFILE_FLAGS) up --build -d

down: guard-mode
	$(DC) $(PROFILE_FLAGS) down -v

stop: guard-mode
	$(DC) $(PROFILE_FLAGS) down

logs: guard-mode
	$(DC) $(PROFILE_FLAGS) logs -f

restart: guard-mode
	$(DC) $(PROFILE_FLAGS) restart

ps: guard-mode
	$(DC) $(PROFILE_FLAGS) ps

build: guard-mode
	$(DC) $(PROFILE_FLAGS) build

# ---------------------------------------------------------------------------
# One-shot mode shortcuts
# ---------------------------------------------------------------------------
dev: configure-dev
	$(MAKE) up logs

dev-backend: configure-dev
	$(MAKE) up logs

dev-full: configure-full
	$(MAKE) up logs

prod: configure-prod
	$(MAKE) up logs

# ---------------------------------------------------------------------------
# Image builds / formatting (unchanged helpers)
# ---------------------------------------------------------------------------
build-backend:
	docker build -t daily-energy-backend:local ./backend

build-frontend:
	docker build -t daily-energy-frontend:local ./frontend

format:
	@command -v gofmt >/dev/null 2>&1 && find . -name '*.go' -exec gofmt -s -w {} + || true
	@command -v npx   >/dev/null 2>&1 && (cd frontend && npx prettier --write "src/**/*.{ts,tsx,css}") || true
